name: Check approval

on:
  pull_request_review:
    types: [submitted]

env:
  BRANCH: ${{ github.base_ref }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}

jobs:
  approved-actions:
    name: Check approval
    runs-on: ubuntu-latest
    steps:
      - name: Judge
        run: |
          if [ "${{ github.event.review.state }}" != "approved" ]; then
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Check bypass
        id: check-bypass
        uses: ./.github/actions/check-bypass
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          workflow-name: approval

      - name: Display required approvers and check
        if: steps.check-bypass.outputs.can_skip != 'true'
        run: |
          git switch -c test
          git remote add upstream https://github.com/PaddlePaddle/Paddle.git
          git fetch upstream $BRANCH
          bash ci/check_approval.sh
