name: Centos-Check

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Clone:
    # Don't run on forked repos.
    name: Clone Paddle
    if: github.repository_owner == 'PaddlePaddle'
    runs-on: test-centos7

    steps:
    - name: Clone paddle
      run: ls
